### ISSUE TITLE
kedro viz not able to use host=0.0.0.0 for open access

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro-viz#255]
## Description
Kedro viz not able to open to public access?

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce

1. kedro viz --host=0.0.0.0
![image](https://user-images.githubusercontent.com/18221871/91694690-94fa9900-eb9f-11ea-9033-eb74d9b88de9.png)

## Expected Result
It can be access with host=0.0.0.0

## Actual Result
The server stuck at first log message, and not able top open the viz.
![image](https://user-images.githubusercontent.com/18221871/91694729-a348b500-eb9f-11ea-9af1-cab4ca2febc8.png)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Kedro 0.16.4

**Comment by noklam** [comment]
closed the issue, i simply replace 0.0.0.0 with my actual ip and it should work.

**Comment by richardwestenra** [comment]
@noklam  Hey sorry for the delay in responding, looks like this fell through the cracks! I see that you've found a workaround, but in any event I've created a JIRA ticket to ensure that this issue is escalated, and I'm going to see if we can assign this to one of our python devs to take a look at - either to improve the CLI or else document it better. Thanks for reporting!

**Comment by noklam** [comment]
in this case, I don't think it is a bug on kedro side. Some unknown thing blocked the program, only after I hit some keybord stroke it continues to run.
