### ISSUE TITLE
Run kedro-viz on a server based on GitHub repo

### ISSUE THREAD

**Issue by hec10r** [quantumblacklabs/kedro-viz#299]
## Description
It would be nice to have the option of run kedro-viz on a server and update the visualization according to the changes in the code. 

## Context
When working in large teams sometimes it is necessary to have an actual picture of how is the current code. Now, as a team, we keep a screenshot of the pipeline in confluence, but when multiple changes occurring, it is difficult to keep it up to date.

## Possible Implementation
Somehow have a CI, who updates the server where kedro-viz is running with the current changes each time there is a commit on master.

## Possible Alternatives
An alternative could be to have a _debug_ mode, that works like this: when running locally, each time that there is a change in the pipeline, reload the server with the new changes `kedro-viz --debug=true`  

## Checklist

- [x] Include labels so that we can categorize your feature request

**Comment by limdauto** [comment]
Hi @hec10r, what you suggested makes sense, but it's up to you to implement this CI process. It depends on how you are running viz on a server. For example, if you are running it in a container, every time there is a code change in master, you can build a new image with new pipeline code and replace the running container with the new one.

If you can give us more information on how you are running viz on a server, we can think of the most optimal way.

**Comment by richardwestenra** [comment]
Hey @hec10r, thanks for getting in touch! Just adding to what Lim wrote: The short answer is that this isn't on our current roadmap, and having discussed it with the team, we think it's unlikely to be a priority, as it is very dependent on your individual setup, so it's best for you to handle yourself. However there are several different ways that you can set this up yourself, and I can point you in a few different directions.

You can run kedro-viz on a server at a root port (so that it can be accessed at a regular live web page) using `sudo kedro viz --port=80`. This will run the data API, and serve viz at `127.0.0.1` You can customise the host with `--host`. You could potentially set up a CI to run this on a live web server.

Alternatively, you could import kedro-viz as a React component into an existing React application. @WaylonWalker has created a Python implementation that does this, and published it as a package: https://pypi.org/project/kedro-static-viz/

For the automatic updates based on your code updates, you could set up a regular cron job to restart the server, or you could find a package/CLI command that will watch your code directory and re-run the viz server when the code is updated. This is something we could look into doing if there is sufficient interest, but it's not a high priority. If other users are interested in this feature, I'd encourage them to drop a 👍 on this issue. For now, I'm going to close it.

**Comment by hec10r** [comment]
Hi guys, thanks for the response. I am not actually running it on a server. It just was an idea that came to my mind while working on a project.

Evidently, I am not an expert, and the CI suggestion was just to exemplify a situation where the feature could be useful. My actual request is to have this `--debug` option, so it would be possible to see in real-time how changes in the code affect the pipeline. I understand that, as @richardwestenra says, it is not high-priority, but please take it into account for future releases :)
