### ISSUE TITLE
Change Node icon by JS

### ISSUE THREAD

**Issue by MinnyKuan** [quantumblacklabs/kedro-viz#311]
## Description
I use npm install Kedro-viz, how can I change node icon by using JS or using antd icon to cover it

![image](https://user-images.githubusercontent.com/74747729/99749566-c12c1300-2b19-11eb-9b7d-32c64e68f09e.png)

**Comment by richardwestenra** [comment]
Hey @MinnyKuan! Sorry, custom icons is not currently a feature that we offer, and honestly I think it's unlikely to happen in the near term, but we will consider it for the future. What are you using the Kedro-Viz npm package for? We'd love to see/hear what you're working on.

In terms of customising the icon yourself, ~I imagine the best way to do it would be with custom CSS rules that would override the default icons~ actually sorry no, that won't work because SVG doesn't support background-image. Damn, sorry.
There are ways of changing it with JS, e.g. attaching various event handlers and updating all the icons in the DOM whenever something changes. However it might not be very performant. But you could give it a try.

**Comment by richardwestenra** [comment]
Oh by the way: better suggestion might be for you to fork Kedro-Viz and add the new icons yourself. The icons are set in [/src/components/icons/node-icon.js](https://github.com/quantumblacklabs/kedro-viz/blob/main/src/components/icons/node-icon.js)

**Comment by MinnyKuan** [comment]
Thanks for your reply :)
I want to use it for table association,something like E-R Diagram.
I will fork it to do so, Thanks~
